class/urls.py
from django.urls import path, include

from . import views



app_name="class"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('rule/', views.RuleView.as_view(), name="rule"),
    path('create/', views.Create_account.as_view(), name="create_account"),
    path('login/', views.Account_login.as_view(), name="login"),
    path('login/topic/', views.TopicView.as_view(), name="topic" ),
    path('login/topic/topic_1.html/', views.TopicList_1_1.as_view(), name="topic_1_1"),
    path('login/topic/topic_2.html/', views.TopicList_1_2.as_view(), name="topic_1_2"),
    path('login/topic/topic_3.html/', views.TopicList_1_3.as_view(), name="topic_1_3"),
    path('login/topic/topic_4.html/', views.TopicList_1_4.as_view(), name="topic_1_4"),
    path('login/topic/topic_5.html/', views.TopicList_1_5.as_view(), name="topic_1_5"),
    path('login/topic/topic_6.html/', views.TopicList_1_6.as_view(), name="topic_1_6"),
    path('login/topic/topic_1.html/<int:pk>/', views.detail_1_1, name="detail_1_1"),
    path('login/topic/topic_2.html/<int:pk>/', views.detail_1_2, name="detail_1_2"),
    path('login/topic/topic_3.html/<int:pk>/', views.detail_1_3, name="detail_1_3"),
    path('login/topic/topic_4.html/<int:pk>/', views.detail_1_4, name="detail_1_4"),
    path('login/topic/topic_5.html/<int:pk>/', views.detail_1_5, name="detail_1_5"),
    path('login/topic/topic_6.html/<int:pk>/', views.detail_1_6, name="detail_1_6"),
    path('login/topic/topic_1.html/<int:pk>/create/', views.CommentCreate_1.as_view(), name="comment_1"),
    path('login/topic/topic_2.html/<int:pk>/create/', views.CommentCreate_2.as_view(), name="comment_2"),
    path('login/topic/topic_3.html/<int:pk>/create/', views.CommentCreate_3.as_view(), name="comment_3"),
    path('login/topic/topic_4.html/<int:pk>/create/', views.CommentCreate_4.as_view(), name="comment_4"),
    path('login/topic/topic_5.html/<int:pk>/create/', views.CommentCreate_5.as_view(), name="comment_5"),
    path('login/topic/topic_6.html/<int:pk>/create/', views.CommentCreate_6.as_view(), name="comment_6"),
]

ycu_class/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('class.urls')),
]

templates/comment_form.html
{% load static %}
{% load widget_tweaks %}
<head>
    <meta charset="UTF-8">
    <title>口コミ追加</title>
    <meta name="description" content="この授業取ろうかな？を解決">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link rel="stylesheet" href="/static/style.css" >
    <link rel="icon" type="image/png" href="/static/favicon.png">
</head>
<body>

 <div class="container col-lg-6 offset-lg-3">

    <!---記事タイトルを表示-->
    <h2 class=title-comment>ユーザ名、口コミ、履修年度(半角数字)を入力してください。</h2>
    <form action="" method="POST" id="comment-form">

        {{ form.non_field_errors }}

        <!--フォームの各フィールドを取り出す-->
        {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}

            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <div class="row my-3">
            <button type="submit" class="btn btn-success col-3 offset-2">投稿する</button>
            <a class="cancel" href="../">キャンセル</a>
        </div>
    </form>
 </div>
</body>

templates/create.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>ユーザー登録</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <h1 class="tino">会員登録</h1>
        <form method="POST" action="{% url 'class:create_account' %}">
            {% csrf_token %}
            <label>ユーザー名</label>
            {{ form.username }}
            <label>パスワード</label>
            {{ form.password1 }}
            <label>パスワード(再入力)</label>
            {{ form.password2 }}
           <button type = "submit"><span>会員登録</span></button>
        </form>
    </body>
    <footer class="er"> 
        <h1 class="foot">@nohakai2001 django-python</h1>
    </footer>
<html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>YCU-class</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="rule/">利用する前に</a></li>
                <li class="menu"><a href="create/">会員登録</a></li>
                <li class="menu"><a href="login/">ログイン</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class="title">この授業取ろうかな？を解決</h1>
            <img src=static/app_ycuclass.png alt="ycu_tips">
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>ログイン</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <h1 class="tino">ログイン</h1>
        {% if form.errors %}
        <p>ユーザー名、パスワードが一致しません</p>
        {% endif %}
        <form method="POST" action="{% url 'class:login' %}">
            {% csrf_token %}
            <label>ユーザー名</label>
            {{ form.username }}
            {{ form.username.errors }}
            <label>パスワード</label>
            {{ form.password }}
            {{ form.password.errors }}
            <button type = "submit"><span>ログイン</span></button>
        </form>
    </body>
    <footer class="er"> 
        <h1 class="foot">@nohakai2001 django-python</h1>
    </footer>
<html>

templates/top.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>トップ</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>     
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="/">ログアウト</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class=important>理学部</h1>
            <ul>
               <li class="rulemenu"><a href="topic_1.html/">１年-必修</a></li>
               <li class="rulemenu"><a href="topic_2.html/">１年-選択必修</a></li>
               <li class="rulemenu"><a href="topic_3.html/">２年-必修</a></li>
               <li class="rulemenu"><a href="topic_4.html/">２年-専門科目</a></li>
               <li class="rulemenu"><a href="topic_5.html/">３年-必修</a></li>
               <li class="rulemenu"><a href="topic_6.html/">３年-専門</a></li>
            </ul>
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_3.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>理学部２年-必修</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>     
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="/login/topic/">トップへ</a></li>
                <li class="menu"><a href="/">ログアウト</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class=important>理学部-２年-必修</h1>
            <ul>
                <tbody>
                    <div class="class-list">
                        <h1>一覧</h1>
                    {% for topic in topic_list_1_3 %}
                  <div class='mt-2'><a href="{{ topic.id }}/">{{ topic | linebreaks | urlize }}</a></div>
                    {% endfor %}
                    </div>
                </tbody>
            </ul>
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_4.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>理学部２年-専門</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>     
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="/login/topic/">トップへ</a></li>
                <li class="menu"><a href="/">ログアウト</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class=important>理学部-２年-専門</h1>
            <ul>
                <tbody>
                    <div class="class-list">
                        <h1>一覧</h1>
                    {% for topic in topic_list_1_4 %}
                  <div class='mt-2'><a href="{{ topic.id }}/">{{ topic | linebreaks | urlize }}</a></div>
                    {% endfor %}
                    </div>
                </tbody>
            </ul>
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_5.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>理学部３年-必修</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>     
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="/login/topic/">トップへ</a></li>
                <li class="menu"><a href="/">ログアウト</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class=important>理学部-３年-必修</h1>
            <ul>
                <tbody>
                    <div class="class-list">
                        <h1>一覧</h1>
                    {% for topic in topic_list_1_5 %}
                  <div class='mt-2'><a href="{{ topic.id }}/">{{ topic | linebreaks | urlize }}</a></div>
                    {% endfor %}
                    </div>
                </tbody>
            </ul>
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_6.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>理学部３年-専門</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">
            <h1 class="logo"><a href="/">YCU-class</a></h1>     
            <nav>
            <ul class="menubar">
                <li class="menu"><a href="/login/topic/">トップへ</a></li>
                <li class="menu"><a href="/">ログアウト</a></li>
            </ul>
            </nav>
        </header>
        <main>
            <h1 class=important>理学部-３年-専門</h1>
            <ul>
                <tbody>
                    <div class="class-list">
                        <h1>一覧</h1>
                    {% for topic in topic_list_1_6 %}
                  <div class='mt-2'><a href="{{ topic.id }}/">{{ topic | linebreaks | urlize }}</a></div>
                    {% endfor %}
                    </div>
                </tbody>
            </ul>
        </main>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_detail_1_2.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>授業詳細</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">    
            <nav class="menupop">
            <ul class="menubar idea">
                <li class="menu"><a href="../">ひとつ前にもどる</a></li>
            </ul>
            </nav>
            <body>
                {% if user.id %}
                <p>ログインしました</p>
                {% endif %}
            <div class="thread kokoa">
                <tr class="kokoa"><td class="syaro">{{ thread_1_2.title }}</td></tr>
            </div>
        </header>
        <main>
            {% for comment in comments_1_2 %}
            <div class="comment-list">
                <div class="border-bottom">{{ comment.name }}_____{{ comment.year }}</div>
                <div class='mt-2'>{{ comment.text | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p></p>
            {% endfor %}
        </main>
        <section class="comment">
            <a href="create/">口コミ追加</a>
        </section>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_detail_1_3.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>授業詳細</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">    
            <nav class="menupop">
            <ul class="menubar idea">
                <li class="menu"><a href="../">ひとつ前にもどる</a></li>
            </ul>
            </nav>
            <body>
                {% if user.id %}
                <p>ログインしました</p>
                {% endif %}
            <div class="thread kokoa">
                <tr class="kokoa"><td class="syaro">{{ thread_1_3.title }}</td></tr>
            </div>
        </header>
        <main>
            {% for comment in comments_1_3 %}
            <div class="comment-list">
                <div class="border-bottom">{{ comment.name }}_____{{ comment.year }}</div>
                <div class='mt-2'>{{ comment.text | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p></p>
            {% endfor %}
        </main>
        <section class="comment">
            <a href='create/'>口コミを追加</a>
        </section>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_detail_1_4.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>授業詳細</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">    
            <nav class="menupop">
            <ul class="menubar idea">
                <li class="menu"><a href="../">ひとつ前にもどる</a></li>
            </ul>
            </nav>
            <body>
                {% if user.id %}
                <p>ログインしました</p>
                {% endif %}
            <div class="thread kokoa">
                <tr class="kokoa"><td class="syaro">{{ thread_1_4.title }}</td></tr>
            </div>
        </header>
        <main>
            {% for comment in comments_1_4 %}
            <div class="comment-list">
                <div class="border-bottom">{{ comment.name }}_____{{ comment.year }}</div>
                <div class='mt-2'>{{ comment.text | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p></p>
            {% endfor %}
        </main>
        <section class="comment">
            <a href='create/'>口コミを追加</a>
        </section>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_detail_1_5.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>授業詳細</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">    
            <nav class="menupop">
            <ul class="menubar idea">
                <li class="menu"><a href="../">ひとつ前にもどる</a></li>
            </ul>
            </nav>
            <body>
                {% if user.id %}
                <p>ログインしました</p>
                {% endif %}
            <div class="thread kokoa">
                <tr class="kokoa"><td class="syaro">{{ thread_1_5.title }}</td></tr>
            </div>
        </header>
        <main>
            {% for comment in comments_1_5 %}
            <div class="comment-list">
                <div class="border-bottom">{{ comment.name }}_____{{ comment.year }}</div>
                <div class='mt-2'>{{ comment.text | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p></p>
            {% endfor %}
        </main>
        <section class="comment">
            <a href='create/'>口コミを追加</a>
        </section>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>

templates/topic_detail_1_6.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>授業詳細</title>
        <meta name="description" content="この授業取ろうかな？を解決">
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="/static/style.css" >
        <link rel="icon" type="image/png" href="/static/favicon.png">
    </head>
    <body>
        <header class="page-header wrapper">    
            <nav class="menupop">
            <ul class="menubar idea">
                <li class="menu"><a href="../">ひとつ前にもどる</a></li>
            </ul>
            </nav>
            <body>
                {% if user.id %}
                <p>ログインしました</p>
                {% endif %}
            <div class="thread kokoa">
                <tr class="kokoa"><td class="syaro">{{ thread_1_6.title }}</td></tr>
            </div>
        </header>
        <main>
            {% for comment in comments_1_6 %}
            <div class="comment-list">
                <div class="border-bottom">{{ comment.name }}_____{{ comment.year }}</div>
                <div class='mt-2'>{{ comment.text | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p></p>
            {% endfor %}
        </main>
        <section class="comment">
            <a href='create/'>口コミを追加</a>
        </section>
        <footer class="er"> 
            <h1 class="foot">@nohakai2001 django-python</h1>
        </footer>
    </body>
</html>